import Login from "./pages/Login.jsx";
import Singup from "./pages/Singup.jsx";
import   Header   from "./componenets/Header/Header.jsx";
import   Footer from "./componenets/Footer/Footer.jsx";
 import  AdminDashbord  from './pages/admin/AdminDashboard.jsx' ;
import AdminDepartment from "./pages/admin/AdminDepartment.jsx";
import AdminEmployees from "./pages/admin/AdminEmployees.jsx";
import AdminProfile from "./pages/admin/AdminProfile.jsx";
import AdminReports from "./pages/admin/AdminReports.jsx";
import AdminTasks from "./pages/admin/AdminTasks.jsx";
 import EmpolyDashBoard from "./pages/employee/EmpolyDashboard.jsx";
import Annoucments from "./pages/employee/Annoucments.jsx";
import Colleagues from "./pages/employee/Colleagues.jsx";
import EmployeeLeave from "./pages/employee/Leave.jsx";
import EmployeeSchedule from "./pages/employee/Schedule.jsx";
import EmployeeTasks from "./pages/employee/Tasks.jsx";
 import    DashBordHeader  from './componenets/ui/DashBordHeader.jsx'
  import Home from "./pages/Home.jsx";
 import TaskListInfo from "./componenets/ui/TaskListInfo.jsx";
 import TasksList from "./componenets/ui/TaskList.jsx";
 import AdminForm from "./componenets/ui/AdminForm.jsx";
 import success from './componenets/ui/success.jsx'
 import EmployeesList from "./componenets/ui/EmployeesList.jsx";
 import WorkingButtons from "./componenets/ui/WorkingButtons.jsx";
 import FailedButton from "./componenets/ui/FailedButton.jsx";
 import CompletedButton from "./componenets/ui/CompletedButton.jsx";
 import About from "./pages/About.jsx";
 import Settings from "./pages/Settings.jsx";
 import DashBoard from "./componenets/DashBoard/DashBoard.jsx";
 import OverView from "./componenets/DashBoard/OverView.jsx";
export  { Settings,DashBoard,OverView, Login, Singup, Header , EmpolyDashBoard,Footer,AdminDashbord,DashBordHeader , About ,Home,TaskListInfo,TasksList, AdminForm ,success,EmployeesList,FailedButton , CompletedButton , WorkingButtons , AdminDepartment, AdminEmployees, AdminProfile, AdminReports, AdminTasks, Annoucments, Colleagues, EmployeeLeave, EmployeeSchedule, EmployeeTasks   }